---
name: "Nyka Application AMI build & Depolyment"

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      packer_version: "1.9.4"

    steps:
      - name: "Repository Checkout"
        uses: actions/checkout@v3

      - name: "Packer installation"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}

      - name: "Packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "working dir"
        run: |
          pwd
          ls -la

      - name: "Packer validate"
        run: packer validate ./packer/

      - name: "Packer build ami"
        run: packer build ./packer/

